import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from 'next/link'
import Navbar from './components/navbar'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{height:'100px', background:'red'}}>
          <div>
            <Link href="/portfolio">portfolio</Link>
        <Link href="/dashboard/analytics">Analytics</Link>
        <Link href="/dashboard/settings/password">Password</Link>
        <Link href="/dashboard/settings/profile">Profile</Link>
        </div>
        <Navbar/>
        </div>
        
        {children}
        
      </body>
    </html>
  );
}
